# Placeholder for ORM models
# Will define User, Card, Set, CardSet classes here

from ..extensions import db

# Example (empty placeholders)
# class User(db.Model): ...
# class Card(db.Model): ...
# class Set(db.Model): ...
# class CardSet(db.Model): ...
